package org.example.entity.enumeration;

public enum Grade {
    ASSOCIATE_DEGREE,
    UNDERGRADUATE,
    CONTINUOUS_MASTERS_DEGREE,
    DISCONTINUOUS_MASTERS_DEGREE,
    PROFESSIONAL_DOCTORATE,
    CONTINUOUS_DOCTORAL_DEGREE,
    NON_CONTINUOUS_SPECIALIZED_DOCTORATE
}
