package org.example.entity.enumeration;

public enum UniversityType {
    DAILY_STATE_UNIVERSITY,
    PUBLIC_NIGHT_UNIVERSITY,
    NONPROFIT_UNIVERSITY,
    PARDIS_UNIVERSITY,
    EXCESS_CAPACITY,
    PAYAM_NOOR_UNIVERSITY,
    UNIVERSITY_OF_APPLIED_SCIENCES,
    AZAD_UNIVERSITY
}
